# https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

name: Close inactive issues
on:
  workflow_call:

jobs:
  close-issues:
    name: Close inactive issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been inactive for a while, it will be closed soon."
          close-issue-message: |
            This issue has been closed due to inactivity. Usually this is a sign that the issue is either outdated, unclear, or 
            the scope is too big.
            
            Feel free to re-open, in that case it will be groomed again.
            
            Cheers, 
            Your friendly GitHub bot

          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}